[tool.uv.workspace]
members = ["packages/*"]

[tool.uv]
dev-dependencies = [
    "coverage>=7.12.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=5.0.0",
    "ruff>=0.8.0,<0.9",
    "ty>=0.0.1a29",
]

[tool.coverage.run]
omit = [".*", "*/site-packages/*", "**/tests/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover", 
    "raise NotImplementedError", 
    "if __name__ == .__main__.:", 
    "if 0:", 
    "if __name__ == .__main__.:"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = [
  "."
]
filterwarnings = [
  "ignore::DeprecationWarning:testcontainers.core.waiting_utils",
]

[tool.ty.src]
exclude = [
    "**/assets",
]