[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "klab-pytest-toolkit-embedded"
dynamic = ["version"]
description = "Pytest embedded testing fixtures for the Klab Pytest Toolkit"
authors = [{ name = "Burak Kizilkaya", email = "burak.kizilkaya@outlook.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "esptool>=5.1.0",
    "pyserial>=3.5",
    "pytest>=8.3.5",
]

[project.urls]
Changelog = "https://github.com/klab365/klab-pytest-toolkit/blob/main/CHANGELOG.md"
Repository = "https://github.com/klab365/klab-pytest-toolkit"
Issues = "https://github.com/klab365/klab-pytest-toolkit/issues"

[project.entry-points.pytest11]
klab_pytest_toolkit_embedded = "klab_pytest_toolkit_embedded.plugin"

[tool.hatch.version]
path = "src/klab_pytest_toolkit_embedded/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    "tests",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = [
  "."
]
